# Generated by Django 5.2.1 on 2025-05-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0, help_text='Total number of medication units currently available.'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='Total amount of dosage per p                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ill.', max_length=100),
        ),
        migrations.AlterField(
            model_name='medication',
            name='schedule',
            field=models.PositiveIntegerField(help_text='Total amount of medication intakes per day. '),
        ),
    ]
