# Generated by Django 5.2.1 on 2025-05-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medication_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='Total amount of dosage per pill.', max_length=100),
        ),
    ]
