# Generated by Django 5.2.1 on 2025-05-23 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medication_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='interval_unit',
            field=models.CharField(default='hours'),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='interval_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='last_reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
