# Generated by Django 5.2.1 on 2025-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicationreminder_interval_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='daily_meds_taken',
            field=models.IntegerField(default=0),
        ),
    ]
